/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package uas;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static uas.Dashboard.GUKM;
/**
 *
 * @author farha
 */
public class MenuPeminjaman extends javax.swing.JInternalFrame {
    String id;
    /**
     * Creates new form MenuPeminjaman
     */
    public MenuPeminjaman() {
        initComponents();
        tampil_table();
    }
    private void tampil_table(){
        btn_acc.setEnabled(false);
        btn_declice.setEnabled(false);
        
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id");
        tb.addColumn("Nama");
        tb.addColumn("UKM");
        tb.addColumn("Status");
        
        try {
            String query = "SELECT tb_peminjaman.id,tb_anggota.nama,tb_anggota.ukm,tb_peminjaman.status FROM tb_peminjaman join tb_anggota on tb_anggota.nim = tb_peminjaman.id_peminjam WHERE tb_peminjaman.ukm = '"+GUKM+"'";
            java.sql.Connection vcon = (Connection)koneksi.configDB();
            java.sql.Statement statement = vcon.createStatement();
            java.sql.ResultSet result = statement.executeQuery(query);
            
            while (result.next()) {                
                tb.addRow(new Object[]{
                    result.getString(1),result.getString(2),result.getString(3),result.getString(4)
                });
            }
            tb_peminjaman.setModel(tb);
        } catch (Exception e) {
        }
    }
    private void tampil_detail(){
        
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id");
        tb.addColumn("Barang");
        tb.addColumn("Jumlah");
        
        try {
            String query = "SELECT d.id,b.nama,d.jml_barang FROM tb_detail_peminjaman d join tb_barang b on b.id = d.id_barang  WHERE d.id_peminjaman = '"+id+"'";
            java.sql.Connection vcon = (Connection)koneksi.configDB();
            java.sql.Statement statement = vcon.createStatement();
            java.sql.ResultSet result = statement.executeQuery(query);
            
            while (result.next()) {                
                tb.addRow(new Object[]{
                    result.getString(1),result.getString(2),result.getString(3)
                });
            }
            tb_detail.setModel(tb);
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_peminjaman = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_detail = new javax.swing.JTable();
        btn_declice = new javax.swing.JButton();
        btn_acc = new javax.swing.JButton();

        setClosable(true);

        tb_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "UKM", "Status"
            }
        ));
        tb_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_peminjaman);

        tb_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Barang", "Jumlah"
            }
        ));
        jScrollPane2.setViewportView(tb_detail);

        btn_declice.setText("Declice");
        btn_declice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decliceActionPerformed(evt);
            }
        });

        btn_acc.setText("Accept");
        btn_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_acc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_declice)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_declice)
                    .addComponent(btn_acc))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_peminjamanMouseClicked
        // TODO add your handling code here:
        int baris = tb_peminjaman.rowAtPoint(evt.getPoint());
        
        id = tb_peminjaman.getValueAt(baris, 0).toString();
        String status = tb_peminjaman.getValueAt(baris, 3).toString();
        
        if ("Declice".equals(status)) {
            btn_acc.setEnabled(false);
            btn_declice.setEnabled(false);
        } else {
            btn_acc.setEnabled(true);
            btn_declice.setEnabled(true);
        }
        
        tampil_detail();
    }//GEN-LAST:event_tb_peminjamanMouseClicked

    private void btn_decliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decliceActionPerformed
        // TODO add your handling code here:
        try {
            String query = "UPDATE tb_peminjaman SET status = 'Declice' WHERE id = '"+id+"'";
            java.sql.Connection vcon = (Connection)koneksi.configDB();
            java.sql.PreparedStatement preStatement = vcon.prepareStatement(query);
            preStatement.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_table();
    }//GEN-LAST:event_btn_decliceActionPerformed

    private void btn_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accActionPerformed
        // TODO add your handling code here:
        try {
            String query = "UPDATE tb_peminjaman SET status = 'Accept' WHERE id = '"+id+"'";
            java.sql.Connection vcon = (Connection)koneksi.configDB();
            java.sql.PreparedStatement preStatement = vcon.prepareStatement(query);
            preStatement.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_table();
    }//GEN-LAST:event_btn_accActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acc;
    private javax.swing.JButton btn_declice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_detail;
    private javax.swing.JTable tb_peminjaman;
    // End of variables declaration//GEN-END:variables
}
